
const Products = [
  {
    id: 1,
    title: "Air Max 270",
    price: 200,
    rating:'★ ★ ★ ★ ☆',
    description: "A perfect blend of style and comfort, the Air Max 270 is designed for all-day wear.",
    Tagline: 'Bestseller',
    size: "EU38 EU39 EU40 EU41",
    image: '/images/shoe52.jpg',
    category: "Running",
    gender: 'Men'
  },
  {
    id: 2,
    title: "Adidas 200",
    price: 250,
    rating:'★ ★ ★ ☆',
    description: "Experience the ultimate in performance with the Adidas 200, engineered for speed and agility.",
    Tagline: 'New',
    size: "EU38 EU39 EU40 EU41",
    image: '/images/shoe6.jpg',
    category: "Running",
    gender: 'Men'
  },
  {
    id: 3,
    title: "Adidas 300",
    price: 250,
    rating:'★ ★ ★ ★ ☆',
    description: "Step up your game with the Adidas 300, Woaturing advanced cushioning and support.",
    Tagline: 'New',
    size: "EU38 EU39 EU40 EU41",
    image: '/images/shoe3.jpg',
    category: "Running",
    gender: 'Men'
  },
    {
    id: 4,
    title: "New Balance ",
    price: 300,
    rating:'★ ★ ★ ☆',
    description: "Run with confidence in the New Balance, designed for stability and comfort on any terrain.",
    Tagline: 'New',
    size: "EU38 EU39 EU40 EU41",
    image: '/images/shoe4.jpg',
    category: "Running",
    gender: 'Men'
  },
    {
    id: 5,
    title: "Breathable Sneekers",
    price: 150,
    rating:'★ ★ ★ ★ ☆',
    description: "Stay cool and comfortable with our breathable sneakers, perfect for long runs or casual outings.",
    Tagline: 'New',
    size: "EU38 EU39 EU40 EU41",
    image: '/images/shoe5.jpg',
    category: "Running",
    gender: 'Men'
  },
    {
    id: 6,
    title: "Nike",
    price: 350,
    rating:'★ ★ ★ ★ ☆',
    description: "The Nike is a versatile sneaker that combines style and performance, suitable for both workouts and everyday wear.",
    Tagline: 'New',
    size: "EU38 EU39 EU40 EU41",
    image: '/images/shoe2.jpg',
    category: "Casual",
    gender: 'Men'
  },
    {
    id: 7,
    title: "Retro-Sneakers",
    price: 200,
    rating:'★ ★ ★ ☆',
    description: "Embrace the vintage vibe with our Retro-Sneakers, designed for comfort and a classic look.",
    Tagline: 'New',
    size: "EU38 EU39 EU40 EU41",
    image: '/images/shoe7.jpg',
    category: "Casual",
    gender: 'Men'
  },
    {
    id: 8,
    title: "Red Breathable Air-Max",
    price: 350,
    rating:'★ ★ ★ ★ ☆',
    description: "Stand out with the Red Breathable Air-Max, Woaturing a bold design and superior breathability.",
    Tagline: 'New',
    size: "EU38 EU39 EU40 EU41",
    image: '/images/shoe8.jpg',
    category: "Casual",
    gender: 'Men'
  },
    {
    id: 9,
    title: "Air Max 220",
    price: 250,
    rating:'★ ★ ★ ★ ☆',
    description: "The Air Max 220 ofWors a sleek design with maximum comfort, perfect for everyday wear.",
    Tagline: 'New',
    size: "EU38 EU39 EU40 EU41",
    image: '/images/shoe9.jpg',
    category: "Casual",
    gender: 'Men'
  },
    {
    id: 10,
    title: "Bright Coloured Sneakers",
    price: 150,
    rating:'★ ★ ★ ☆',
    description: "Add a pop of color to your wardrobe with our Bright Coloured Sneakers, designed for style and comfort.",
    Tagline: 'New',
    size: "EU38 EU39 EU40 EU41",
    image: '/images/shoe10.jpg',
    category: "Casual",
    gender: 'Men'
  },
    {
    id: 11,
    title: "Black Hightop",
    price: 250,
    rating:'★ ★ ★ ★ ☆', 
    description: "The Black Hightop combines classic style with modern comfort, making it a must-have for any sneaker collection.", 
    Tagline: 'New',
    size: "EU38 EU39 EU40 EU41",      
    image: '/images/shoe11.jpg',
    category: "Formal",
    gender: 'Men'
  },
    {
    id: 12,
    title: "Multi-Colour Hightop",
    price: 300,
    rating:'★ ★ ★ ★ ☆',
    description: "Make a statement with the Multi-Colour Hightop, Woaturing a unique design and comfortable fit.",
    Tagline: 'Bestseller',
    size: "EU38 EU39 EU40 EU41",
    image: '/images/shoe12.jpg',
    category: "Formal",
    gender: 'Men'
  },
    {
    id: 13,
    title: " white Air Max",
    price: 400,
    rating:'★ ★ ★ ★ ☆',
    description: "The White Air Max is a timeless classic that ofWors both style and comfort, perfect for any occasion.",
    Tagline: 'New',
    size: "EU38 EU39 EU40 EU41",
    image: '/images/shoe15.jpg',
    category: "Formal",
    gender: 'Men'
  },
    {
    id: 14,
    title: "Breathable Fly Sneakers",
    price: 300,
    rating:'★ ★ ★ ★ ☆',
    description: "Experience ultimate comfort with our Breathable Fly Sneakers, designed for all-day wear and superior ventilation.",
    Tagline: 'New',
    size: "EU38 EU39 EU40 EU41",
    image: '/images/shoe14.jpg',
    category: "Formal",
    gender: 'Men'
  },
    {
    id: 15,
    title: "Black Air Max 200",
    price: 150,
    rating:'★ ★ ★ ★ ☆',    
    description: "The Black Air Max 200 combines sleek design with advanced cushioning for a comfortable fit.",
    Tagline: 'New',
    size: "EU38 EU39 EU40 EU41",
    image: '/images/shoe13.jpg',
    category: "Sneakers",
    gender: 'Men'
  },
    {
    id: 16,
    title: "Breathable Air Max",
    price: 200,
    rating:'★ ★ ★ ★ ☆',
    description: "Stay active and stylish with our Breathable Air Max, designed for performance and comfort.",
    Tagline: 'Bestseller',
    size: "EU38 EU39 EU40 EU41",
    image: '/images/shoe16.jpg',
    category: "Sneakers",
    gender: 'Men'
    },
    {
    id: 17,
    title: "White-Black Smooth",
    price: 300,
    rating:'★ ★ ★ ★ ☆',
    description: "The White-Black Smooth sneaker ofWors a sleek and modern design, perfect for any casual outfit.",
    Tagline: 'New',
    size: "EU38 EU39 EU40 EU41",
    image: '/images/shoe17.jpg',
    category: "Sneakers",
    gender: 'Men'
  },
    {
    id: 18,
    title: "Fashion Blue Nike",
    price: 400,
    rating:'★ ★ ★ ★ ☆',
    description: "Step out in style with the Fashion Blue Nike, Woaturing a trendy design and comfortable fit.",
    Tagline: 'New',
    size: "EU38 EU39 EU40 EU41",
    image: '/images/shoe18.jpg',
    category: "Sneakers",
    gender: 'Men'
  },
    {
    id: 19,
    title: "Pink-White Nike",
    price: 400,
    rating:'★ ★ ★ ★ ☆',
    description: "The Pink-White Nike sneaker combines a stylish look with exceptional comfort, perfect for everyday wear.",
    Tagline: 'New',
    size: "EU38 EU39 EU40 EU41",
    image: '/images/shoe19.jpg',
    category: "Sneakers",
    gender: 'Men'
  },
    {
    id: 20,
    title: "Ladies High-Heel",
    price: 500,
    rating:'★ ★ ★ ★ ☆',
    description: "Elevate your style with our Ladies High-Heel, designed for elegance and comfort.",
    Tagline: 'New',
    size: "EU38 EU39 EU40 EU41",
    image: '/images/shoe20.jpg',
    category: "Formal",
    gender: 'Women'
  },
      {
    id: 21,
    title: "Ladies Sneakers",
    price: 300,
    rating:'★ ★ ★ ☆',
    description: 'Step out in style with the Fashion ladies sneakers, Woaturing a trendy design and comfortable fit.',
    Tagline: 'New',
    size: "EU38 EU39 EU40 EU41",
    image: '/images/shoe21.jpg',
    category: "Casual",
    gender: 'Women'
  },
      {
    id: 22,
    title: "Ladies High-Heel",
    price: 400,
    rating:'★ ★ ★ ☆',
    description: "Elevate your style with our Ladies High-Heel, designed for elegance and comfort.",
    Tagline: 'Bestseller',
    size: "EU38 EU39 EU40 EU41",
    image: '/images/shoe22.jpg',
    category: "Formal",
    gender: 'Women'
  },
      {
    id: 23,
    title: "Ladies High-Heel",
    price: 500,
    rating:'★ ★ ★ ☆',
    description: "Elevate your style with our Ladies High-Heel, designed for elegance and comfort.",
    Tagline: 'New',
    size: "EU38 EU39 EU40 EU41",
    image: '/images/shoe23.jpg',
    category: "Formal",
    gender: 'Women'
  },
      {
    id: 24,
    title:  "Ladies Casual High-Heel",
    price: 550,
    rating:'★ ★ ★ ☆',
    description: "Elevate your style with our Ladies Casual High-Heel, designed for elegance and comfort.",
    Tagline: 'New',
    size: "EU38 EU39 EU40 EU41",
    image: '/images/shoe24.jpg',
    category: "Casual",
    gender: 'Women'
  },
      {
    id: 25,
    title: "Ladies High-Heel",
    price: 600,
    rating:'★ ★ ★ ☆',
    description: 'Step out in style with the Fashion ladies high-heel, Woaturing a trendy design and comfortable fit.',
    Tagline: 'New',
    size: "EU38 EU39 EU40 EU41",
    image: '/images/shoe25.jpg',
    category: "Formal",
    gender: 'Women'
  },
      {
    id: 26,
    title: "Ladies Sneakers",
    price: 250,
    rating:'★ ★ ★ ☆',
    description: 'Step out in style with the Fashion ladies sneakers, Woaturing a trendy design and comfortable fit.',
    Tagline: 'New',
    size: "EU38 EU39 EU40 EU41",
    image: '/images/shoe26.jpg',
    category: "Sneakers",
    gender: 'Wonen'
  },
      {
    id: 27,
    title: "Ladies High Boot",
    price: 450,
    rating:'★ ★ ★ ☆',
    description: 'Step out in style with the Fashion ladies high-boot, Woaturing a trendy design and comfortable fit.',
    Tagline: 'Bestseller',
    size: "EU38 EU39 EU40 EU41",
    image: '/images/shoe27.jpg',
    category: "Formal",
    gender: 'Women'
  },
      {
    id: 28,
    title: "Ladies Sneakers",
    price: 350,
    rating:'★ ★ ★ ☆',
    description: 'Step out in style with the Fashion ladies sneakers, Woaturing a trendy design and comfortable fit.',
    Tagline: 'New',
    size: "EU38 EU39 EU40 EU41",
    image: '/images/shoe28.jpg',
    category: "Sneakers",
    gender: 'Women'
  },
      {
    id: 29,
    title: "Ladies High Casual Boots",
    price: 400,
    rating:'★ ★ ★ ☆',
    description: 'Step out in style with the Fashion ladies high casual boots, Woaturing a trendy design and comfortable fit.',
    Tagline: 'New',
    size: "EU38 EU39 EU40 EU41",
    image: '/images/shoe29.jpg',
    category: "Casual",
    gender: 'Women'
  },
      {
    id: 30,
    title: "Ladies Sneakers",
    price: 200,
    rating:'★ ★ ★ ☆',
    description: 'Step out in style with the Fashion ladies sneakers, Woaturing a trendy design and comfortable fit.',
    Tagline: 'New',
    size: "EU38 EU39 EU40 EU41",
    image: '/images/shoe30.jpg',
    category: "Sneakers",
    gender: 'Women'
  },
      {
    id: 31,
    title: "Ladies High-Heel Multi",
    price: 500,
    rating:'★ ★ ★ ☆',
    description: 'Step out in style with the Fashion ladies high-heel multi, Woaturing a trendy design and comfortable fit.',
    Tagline: 'Bestseller',
    size: "EU38 EU39 EU40 EU41",
    image: '/images/shoe31.jpg',
    category: "Formal",
    gender: 'Women'
  },
    {
    id: 32,
    title: "Brown Men's Leather",
    price: 550,
    rating:'★ ★ ★ ★ ☆',
    description: "A perfect blend of style and comfort, the Brown Men's Leather is designed for all-day wear.",
    Tagline: 'Bestseller',
    size: "EU38 EU39 EU40 EU41",
    image: '/images/shoe43.jpg',
    category: "Formal",
    gender: 'Men'
  },
    {
    id: 33,
    title: "Black Men's Leather",
    price: 400,
    rating:'★ ★ ★ ★ ☆',
    description: "A perfect blend of style and comfort, the Black Men's Leather is designed for all-day wear.",
    Tagline:'Bestseller',
    size: "EU38 EU39 EU40 EU41",
    image: '/images/shoe44.jpg',
    category: "Formal",
    gender: 'Men'
  },
    {
    id: 34,
    title: "Brown Men's Leather",
    price: 350,
    rating:'★ ★ ★ ★ ☆',
    description: "A perfect blend of style and comfort, the Brown Men's Leather is designed for all-day wear.",
    Tagline: 'New',
    size: "EU38 EU39 EU40 EU41",
    image: '/images/shoe45.jpg',
    category: "Formal",
    gender: 'Men'
  },
    {
    id: 35,
    title: "Brown Men's Leather",
    price: 400,
    rating:'★ ★ ★ ★ ☆',
    description: "A perfect blend of style and comfort, the Brown Men's Leather is designed for all-day wear.",
    Tagline: 'New',
    size: "EU38 EU39 EU40 EU41",
    image: '/images/shoe46.jpg',
    category: "Formal",
    gender: 'Men'
  },
    {
    id: 36,
    title: "Dark Brown Men's Leather",
    price: 450,
    rating:'★ ★ ★ ★ ☆',
    description: "A perfect blend of style and comfort, the Dark Brown Men's Leather is designed for all-day wear.",
    Tagline: 'New',
    size: "EU38 EU39 EU40 EU41",
    image: '/images/shoe47.jpg',
    category: "Formal",
    gender: 'Men'
  },
    {
    id: 37,
    title: "Brown Men's Leather",
    price: 350,
    rating:'★ ★ ★ ★ ☆',
    description: "A perfect blend of style and comfort, the Brown Men's Leather is designed for all-day wear.",
    Tagline: 'New',
    size: "EU38 EU39 EU40 EU41",
    image: '/images/shoe48.jpg',
    category: "Formal",
    gender: 'Men'
  },
    {
    id: 38,
    title: "White Casual Men's Flat",
    price: 350,
    rating:'★ ★ ★ ★ ☆',
    description: "A perfect blend of style and comfort, the White Casual Men's Flat is designed for all-day wear.",
    Tagline: 'New',
    size: "EU38 EU39 EU40 EU41",
    image: '/images/shoe49.jpg',
    category: "Casual",
    gender: 'Men'
  },
    {
    id: 39,
    title: "Black Men's Leather",
    price: 450,
    rating:'★ ★ ★ ★ ☆',
    description: "A perfect blend of style and comfort, the Black Men's Leather is designed for all-day wear.",
    Tagline: 'New',
    size: "EU38 EU39 EU40 EU41",
    image: '/images/shoe50.jpg',
    category: "Formal",
    gender: 'Men'
  },
    {
    id: 40,
    title: "Casual Men's Flat",
    price: 350,
    rating:'★ ★ ★ ★ ☆',
    description: "A perfect blend of style and comfort, the Casual Men's Flat is designed for all-day wear.",
    Tagline: 'New',
    size: "EU38 EU39 EU40 EU41",
    image: '/images/shoe51.jpg',
    category: "Casual",
    gender: 'Men'
  },
    {
    id: 41,
    title: "Air Max 270",
    price: 200,
    rating:'★ ★ ★ ★ ☆',
    description: "A perfect blend of style and comfort, the Air Max 270 is designed for all-day wear.",
    Tagline: 'New',
    size: "EU38 EU39 EU40 EU41",
    image: '/images/shoe1.jpg',
    category: "Running",
    gender: 'Men'
  },
    {
    id: 42,
    title: "Casual Men's Flat",
    price: 350,
    rating:'★ ★ ★ ★ ☆',
    description: "A perfect blend of style and comfort, the Casual Men's Flat is designed for all-day wear.",
    Tagline: 'New',
    size: "EU38 EU39 EU40 EU41",
    image: '/images/shoe53.jpg',
    category: "Casual",
    gender: 'Men'
  },
    {
    id: 43,
    title: "Casual Men's Flat",
    price: 350,
    rating:'★ ★ ★ ★ ☆',
    description: "A perfect blend of style and comfort, the Casual Men's Flat is designed for all-day wear.",
    Tagline: 'New',
    size: "EU38 EU39 EU40 EU41",
    image: '/images/shoe54.jpg',
    category: "Casual",
    gender: 'Men'
  },
      {
    id: 44,
    title: "Kiddies stylish Shoe",
    price: 150,
    rating:'★ ★ ★ ★ ☆',
    description: "Girls and boys smart and practical shoe for kids. Easy to get on, and keep on",
    Tagline: 'Bestseller',
    size: "EU38 EU39 EU40 EU41",
    image: '/images/shoe32.jpg',
    category: "Kids",
    gender: 'Kids',
  },
     {
    id: 45,
    title: "Kiddies stylish Shoe",
    price: 100,
    rating:'★ ★ ★ ★ ☆',
    description: "Girls and boys smart and practical shoe for kids. Easy to get on, and keep on",
    Tagline: 'New',
    size: "EU38 EU39 EU40 EU41",
    image: '/images/shoe33.jpg',
    category: "Kids",
    gender: 'Kids',
  },
     {
    id: 46,
    title: "Kiddies stylish Shoe",
    price: 150,
    rating:'★ ★ ★ ★ ☆',
    description: "Girls and boys smart and practical shoe for kids. Easy to get on, and keep on",
    Tagline: 'New',
    size: "EU38 EU39 EU40 EU41",
    image: '/images/shoe34.jpg',
    category: "Kids",
    gender: 'Kids',
  },
     {
    id: 47,
    title: "Kiddies stylish Shoe",
    price: 120,
    rating:'★ ★ ★ ★ ☆',
    description: "Girls and boys smart and practical shoe for kids. Easy to get on, and keep on",
    Tagline: 'New',
    size: "EU38 EU39 EU40 EU41",
    image: '/images/shoe35.jpg',
    category: "Kids",
    gender: 'Kids',
  },
     {
    id: 48,
    title: "Kiddies stylish Shoe",
    price: 150,
    rating:'★ ★ ★ ★ ☆',
    description: "Girls and boys smart and practical shoe for kids. Easy to get on, and keep on",
    Tagline: 'Bestseller',
    size: "EU38 EU39 EU40 EU41",
    image: '/images/shoe36.jpg',
    category: "Kids",
    gender: 'Kids',
  },
     {
    id: 49,
    title: "Kiddies stylish Shoe",
    price: 180,
    rating:'★ ★ ★ ★ ☆',
    description: "Girls and boys smart and practical shoe for kids. Easy to get on, and keep on",
    Tagline: 'New',
    size: "EU38 EU39 EU40 EU41",
    image: '/images/shoe37.jpg',
    category: "Kids",
    gender: 'Kids',
  },
     {
    id: 50,
    title: "Kiddies stylish Shoe",
    price: 120,
    rating:'★ ★ ★ ★ ☆',
    description: "Girls and boys smart and practical shoe for kids. Easy to get on, and keep on",
    Tagline: 'New',
    size: "EU38 EU39 EU40 EU41",
    image: '/images/shoe38.jpg',
    category: "Kids",
    gender: 'Kids',
  },
     {
    id: 51,
    title: "Kiddies stylish Shoe",
    price: 170,
    rating:'★ ★ ★ ★ ☆',
    description: "Girls and boys smart and practical shoe for kids. Easy to get on, and keep on",
    Tagline: 'New',
    size: "EU38 EU39 EU40 EU41",
    image: '/images/shoe39.jpg',
    category: "Kids",
    gender: 'Kids',

  },
     {
    id: 52,
    title: "Kiddies stylish Shoe",
    price: 150,
    rating:'★ ★ ★ ★ ☆',
    description: "Girls and boys smart and practical shoe for kids. Easy to get on, and keep on",
    Tagline: 'New',
    size: "EU38 EU39 EU40 EU41",
    image: '/images/shoe40.jpg',
    category: "Kids",
    gender: 'Kids',
  },
     {
    id: 53,
    title: "Kiddies stylish Shoe",
    price: 130,
    rating:'★ ★ ★ ★ ☆',
    description: "Girls and boys smart and practical shoe for kids. Easy to get on, and keep on",
    Tagline: 'Bestseller',
    size: "EU38 EU39 EU40 EU41",
    image: '/images/shoe41.jpg',
    category: "Kids",
    gender: 'Kids',
  },
     {
    id: 54,
    title: "Kiddies stylish Shoe",
    price: 150,
    rating:'★ ★ ★ ★ ☆',
    description: "Girls and boys smart and practical shoe for kids. Easy to get on, and keep on",
    Tagline: 'New',
    size: "EU38 EU39 EU40 EU41",
    image: '/images/shoe42.jpg',
    category: "Kids",
    gender: 'Kids',
  },
];


export default Products;